version: '3.0'
services:
  nuxt:
    image: node:9.10.0-slim
    volumes:
      - .:/var/opt/app
    working_dir: /var/opt/app
    expose:
      - "4000"
    ports:
      - "4000:3000"
    entrypoint: bash -c
    command: |
      "yarn install && yarn dev"

  storybook:
    image: node:9.10.0-slim
    volumes:
      - .:/var/opt/app
    working_dir: /var/opt/app
    expose:
      - "9002"
    ports:
      - "9002:9001"
    entrypoint: bash -c
    command: |
      "yarn install && yarn storybook"

  static-storybook:
    image: node:9.10.0-slim
    volumes:
      - .:/var/opt/app
    working_dir: /var/opt/app
    expose:
      - "8888"
    ports:
      - "8888:5000"
    entrypoint: bash -c
    command: |
      "yarn install && yarn build-storybook && yarn ss"
